### ISSUE TITLE
The problem of reverse order of items

### ISSUE THREAD

**Issue by TexDash** [arthurdejong/munin-plot#16]
Hi Arthur, Thanks for this great visualization tool!

I just found a minor issue: 
![image](https://github.com/arthurdejong/munin-plot/assets/138767936/07038235-3693-45c2-b099-9010b3d0a7fb)
where the items are suppose to be list from CPU0 to CPU15.

**Comment by arthurdejong** [comment]
Hi @TexDash,

Thanks for pointing this out. It seems that somewhere this changed because the code for some reason had an explicit call to reverse the order. Anyway, it is fixed in ab1dd9a and will be in the next release.

**Comment by TexDash** [comment]
Nice!
