### ISSUE TITLE
Initial setup unclarities; proposing minor fixes

### ISSUE THREAD

**Issue by eudoxos** [arthurdejong/munin-plot#7]
I installed munin-plot on a server already running munin, and I am a bit lost how to configure dashboards (`DASHBOARDS_DIR`) and others.

I managed to run the initial website (without data) by adjusting the suggested Apache2 configuration (it says `<Files web.py>`, should be `<Files wsgi.py>`).

Then I bumped into `cgi.parse_qs` (deprecated since python 3.2) having been removed in python 3.8, in favor of `urllib.parse.parse_qs` (see e.g. https://github.com/eventlet/eventlet/pull/581).

I still get permission denied when accessing data, which might be due to reverse proxy (mis)configuration.

Thank you for your package, I hope it will be useful in the future.

**Comment by arthurdejong** [comment]
Thanks for the ticket. I know I should really improve the installation instructions. I've made some small improvements in 59575fe.

I've replaced `cgi.parse_qs` with `urllib.parse.parse_qs` in 771b839. Thanks for pointing that out.

One thing to consider regarding permissions is that the user running Apache needs to be able to read the munin data files.

munin-plot is at this point mostly a tool that fits my needs. Installation and documentation could be a bit polished further.
